# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: GitHub Actions Demo
on: [pull_request]
jobs:
  Explore-PR-Actions:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.read_results.outputs.contents }}
    steps:
      - name: Gather files changed
        uses: actions/checkout@v2
        with:
          fileOutput: "json"
      - name: Get necessary libraries
        run: pip install publicsuffix2
      - name: Content check
        id: check
        run: python3 check_sites.py > results.txt
      - name: Read the result
        id: read_results
        uses: andstor/file-reader-action@v1
        with:
          path: "results.txt"
      - name: File contents
        run: echo '${{ steps.read_results.outputs.contents }}'
      - name: Fail or Succeed
        if: steps.read_results.outputs.contents != 'success'
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed(${{ steps.read_results.outputs.contents }})
